getwd()
setwd("C:/Users/aaa/Desktop/R/coursera")
data1 <- read.table(file = "C:/Users/aaa/Desktop/R/coursera/household_power_consumption.txt", header = T, sep = ";", na.strings = "?")
data2 <- subset(data1, Date == "1/2/2007" | Date == "2/2/2007")
head(data2)
dim(data2)
names(data2)
mode(data2$Global_active_power)
hist(data2$Global_active_power, xlab = "Global Active Power (kilowatts)", breaks = 12, main = "Global Active Power", col = "red")
png(filename = "plot1.png", width = 480, height = 480, units = "px")
dev.off()
dev.copy(png, file="plot1.png")
dev.off()
